### ISSUE TITLE
Feature request: Dynamic `Content-Type` header option

### ISSUE THREAD

**Issue by maricn** [jakubroztocil/httpcat#2]
How about an option to do the automatic `Content-Type` header calculation based on the body size? It could be an argument to httpcat to enable this header override.
I often find myself editing the body content quickly and request fails due to wrong `Content-Type` value.

**Comment by jkbrzt** [comment]
@maricn this looks like a use-case for the HTTPie `--offline` mode:  https://github.com/httpie/httpcat#httpie-offline-mode
